# Generated by Django 3.0.5 on 2020-04-16 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('postcode', models.CharField(blank=True, max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(blank=True, max_length=250)),
                ('token', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('program', models.CharField(max_length=250)),
                ('checkin_date', models.DateTimeField(auto_now_add=True)),
                ('adults', models.DecimalField(decimal_places=2, max_digits=10)),
                ('children', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time1', models.CharField(blank=True, max_length=255)),
                ('description1', models.TextField(blank=True)),
                ('time2', models.CharField(blank=True, max_length=255)),
                ('description2', models.TextField(blank=True)),
                ('time3', models.CharField(blank=True, max_length=255)),
                ('description3', models.TextField(blank=True)),
                ('time4', models.CharField(blank=True, max_length=255)),
                ('description4', models.TextField(blank=True)),
                ('time5', models.CharField(blank=True, max_length=255)),
                ('description5', models.TextField(blank=True)),
                ('time6', models.CharField(blank=True, max_length=255)),
                ('description6', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promotion_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='program')),
                ('available', models.BooleanField(default=True)),
                ('promotion', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('program_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProgramDetail')),
            ],
        ),
    ]
